--- 
extensions: 
- json
- another-extension
name: TheOracle
bbver: 4.6
sdk: /Users/brian/work/rhodes
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.1.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.2
  entitlements: 
  codesignidentity: 
  configuration: Debug
  emulator: 4.0.1
