--- 
extensions: 
- extension-name-here
- second-extension-name
name: contact
capabilities: 
- gps
bbver: 4.6
android: 
  version: 2.1
  apikey: 0iQD6Wk5WtjLaoD4-g5eXbsfsyNSroB8KmRJkkA
  mapping: true
sdk: /Users/brian/work/rhodes
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.0.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
