--- 
name: contact
extensions: 
- extension-name-here
- second-extension-name
capabilities: 
- gps
bbver: 4.6
sdk: /Users/brian/work/rhodes
android: 
  version: 2.1
  mapping: true
  apikey: 0iQD6Wk5WtjLaoD4-g5eXbsfsyNSroB8KmRJkkA
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.0.0
vendor: rhomobile
iphone: 
  emulator: 4.0.2
  provisionprofile: 
  sdk: iphonesimulator4.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
