--- 
name: androidpush-rhodes
extensions: 
- json
- another-extension
capabilities: 
- push
- vibrate
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.1
android: 
  push: 
    sender: support@rhomobile.com
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.2.1
vendor: rhomobile
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
