#Sources 
:sources: 
  Scontact: 
    :poll_interval: 0
  Saccount: 
    :poll_interval: 0
 
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:development: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
  :iphonecertfile: settings/apple_push_cert.pem
  :iphoneserver: gateway.sandbox.push.apple.com
  :iphoneport: 2195