#Sources 
:sources: 
  Scontact: 
    :poll_interval: 0
  Saccount: 
    :poll_interval: 0
 
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:development: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
